spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  datasource:
    url: jdbc:mysql://localhost:3306/pem?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


server:
  tomcat:
    max-swallow-size: -1
  port: 9080

springdoc:
  swagger-ui:
    path: /definition-documentation
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /pem-api-docs
pem:
  openapi:
    dev-url: http://localhost:9080